#!/usr/bin/env python3
"""Regenerate ``docs/modules.md`` — one line per built-in module, from the data.

    python3 scripts/build_module_index.py [--check | --write]

``docs-onramp/04``. The owner's ask was *"a little brief on each built-in module
and what it does, linked."* Looked: **the briefs already exist.**
``backend/openstategraph/compile/port_specs.json`` carries every node type with
a ``label``, a ``description``, a ``category`` and a ``scope``, and not one of
them is missing a description. ``openstategraph nodes`` prints all of them, one
line each, and is the best summary of this product's vocabulary anywhere in the
repository.

What did not exist was a **page**. On 2026-09-05 thirteen of the forty-three
types were named — by id *or* by display label — in no file under ``docs/``, and
thirty were named in neither form in ``docs/on-the-canvas.md``, the page
``docs/README.md`` routes *"understand what I am drawing"* to. So the gap was
routing, not content, and the fix is a page that **derives** the content rather
than restating it.

**Generated, not typed**, for two reasons and the second is the one that binds:

- a hand-kept second copy of forty-three descriptions is ``CLAUDE.md``'s
  duplication rule broken — the field schema is declared once and card,
  inspector, defaults and validation all derive from it, and a documentation
  page has no claim to be the exception;
- it would be stale within a week. The vocabulary moved by four types in the
  month before this page existed, and nothing would have said so.

Every count on the page is printed from the data this script just read, so the
page states no number a human has to keep true — ``CLAUDE.md``'s rule that a
number in prose has no way to fail, applied to a page whose entire subject is
counts.

## What is derived, and from where

Nothing here restates a brief that has an owner elsewhere:

===========================  ==================================================
node types (43)              ``compile/port_specs.json`` — id, label,
                             description, category, scope
providers                    ``openstategraph.providers.builtin_specs()``
CLI verbs                    ``cli.build_parser()``, the real argparse
MCP tools                    ``@server.tool(name=…)`` in ``mcp_server.py``,
                             read as text so this script needs no ``[mcp]``
bundled agent skills         the directories under ``openstategraph/agent_skills/``
worked examples              ``examples/index.json``
``new`` templates            ``templates/index.json``
===========================  ==================================================

The five families after the first get **one row each**, not a copy of their
pages. ``docs/cli.md`` is 20/20 against the parser and ``docs/mcp.md`` is 18/18
against the server; both are canonical and a second enumeration here would make
``docs/README.md``'s promise of a single place false while satisfying a gate.
What this page adds for them is a count that cannot be wrong and a link.

## The one hand-written table, named

``DEEPER`` below maps a type — or a prefix of one — onto the page that goes
further than a one-line brief. It is hand-written because *"which page explains
this properly"* is a judgement and no field in the data carries it. Scanning
``docs/`` for each type id was priced and rejected: it would make this page's
bytes a function of every other page's prose, so an unrelated sentence added to
``patterns.md`` would fail the drift gate in CI with a diff about node types.
The cost of the judgement is two assertions in
``backend/tests/test_documented_modules_match_the_vocabulary.py``: the target
exists, **and** the target names that module by id or by label outside a fenced
block. Existence alone was not enough, and ``docs-onramp/11`` is the bill —
every link resolved, and 31 of the 43 landed on a page that never mentioned the
card the reader had just clicked. Naming is judged on prose only, because the
row that exposed this was ``tool.platform-read-file``: its id sat in a comment
inside an example document on ``docs/mcp.md``, and nothing written *to* a reader
on that page said what the tool read.

Types with no entry fall back to ``openstategraph nodes <type>``, which prints
the fields and ports as well as the brief, and is never stale by construction.
"""

from __future__ import annotations

import argparse
import difflib
import json
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]
BACKEND = REPO / "backend"
PACKAGE = BACKEND / "openstategraph"
PORT_SPECS = PACKAGE / "compile" / "port_specs.json"
PAGE = REPO / "docs" / "modules.md"

STAMP = "<!-- GENERATED by scripts/build_module_index.py — do not edit by hand. -->"

#: Display order and heading for each `category` the data carries. Order is a
#: reading order, not alphabetical: what starts a flow, what thinks, what it
#: reaches for, what it remembers, what comes out, and what is decoration.
CATEGORIES: tuple[tuple[str, str, str], ...] = (
    (
        "inputs",
        "Inputs — where a run starts",
        "Every flow begins with something the run is *given*. These three are "
        "that something: a prompt typed into the box, a Markdown file of "
        "instructions, or a named rules layer you reuse across workflows. They "
        "call no model and cost nothing; they just hand the first words to "
        "whatever is wired after them.",
    ),
    (
        "agent",
        "Agents and control flow — what decides",
        "This is where the thinking and the branching live. An **AI Agent** is "
        "one model with tools attached. The rest are the shapes you build "
        "*around* it: a router that picks a branch, a grader that sends weak "
        "work back with feedback, an orchestrator that splits a job across "
        "workers, a guard that refuses, a human who approves. Several of them "
        "call no model at all — they run a function you wrote and take the "
        "branch it names, which is cheaper and repeatable.",
    ),
    (
        "tools",
        "Tools — what an agent can reach for",
        "A tool is a capability you plug into an agent's `tools` bus; the agent "
        "decides when to call it. Nothing here runs on its own. They are the "
        "largest family because they are the one you extend most: the database "
        "readers, the web readers, the platform's own introspection, and `MCP "
        "server`, which brings in every tool some other service already "
        "publishes. Writing your own is [building an atom](building-an-atom.md).",
    ),
    (
        "memory",
        "Memory — what survives a step",
        "One card, and it is about *carrying* rather than *storing*: whatever "
        "crosses it is recorded, and the segment's earlier entries are handed "
        "to whatever comes next. Per-topic knowledge an agent looks things up "
        "in is a tool, not this — see `Knowledge` in the tools table.",
    ),
    (
        "resolve",
        "Resolve — deciding before the model does",
        "Two cards that answer a question *before* a model gets to guess at it: "
        "which store should answer this, and what do this domain's words mean. "
        "Both report what they covered as well as what they found, and neither "
        "makes a model call — which is exactly why they exist. A model asked to "
        "pick a source will always pick one.",
    ),
    (
        "output",
        "Output — what a run says",
        "How a finished run presents itself: rendered as Markdown, or a fixed "
        "sentence you wrote for a branch that has to say something without "
        "spending a model call on it.",
    ),
    (
        "compose",
        "Compose — a workflow inside a workflow",
        "One card, and the reason workflows scale past one canvas: another "
        "workflow, mounted as a single step. Task in, answer out. It is "
        "mounted **by reference** — change the original and every mount of it "
        "changes — which is what separates a *package* from a *template*.",
    ),
    (
        "annotate",
        "Annotate — for the humans reading the canvas",
        "Neither of these compiles to anything. They are the labels and frames "
        "that make a canvas readable six months later.",
    ),
)

#: type id, or a prefix ending in `-`/`.`, → the page that goes deeper.
#: Hand-written on purpose; see this module's docstring, §"The one
#: hand-written table, named".
#:
#: A row here is a promise that the target page tells the reader something
#: about *that* module, and `docs-onramp/11` measured what the promise was
#: worth: 31 of the 43 rows landed on a page that named the module in neither
#: form outside a code block, and three of the five targets were written for a
#: different reader — eight rows about running a query pointed at
#: `declaring-a-table.md`, which opens *"for whoever owns a data source"*.
#: A type with **no row here is the honest outcome**, not the leftover one:
#: it falls back to `openstategraph nodes <type>`, which prints the fields and
#: the ports as well as the brief and is never stale by construction. The
#: property is pinned by
#: `backend/tests/test_documented_modules_match_the_vocabulary.py`, which reads
#: each target and fails naming the row and the page.
DEEPER: tuple[tuple[str, str, str], ...] = (
    ("tool.knowledge-lookup", "second-brain.md", "the second brain"),
    ("tool.sql-", "on-the-canvas.md", "the SQL atoms"),
    ("tool.databricks-query", "on-the-canvas.md", "the SQL atoms"),
    ("tool.mssql-query", "on-the-canvas.md", "the SQL atoms"),
    ("tool.mcp", "mcp.md", "the MCP layer"),
    # `docs-onramp/12`. The ten rows `docs-onramp/11` left on the CLI door,
    # because no page was their right home. One now is: `prebuilt-tools.md`
    # is the counterpart of `building-an-atom.md` — that page is for the
    # reader *writing* a tool, this one for the reader *using* one, and it
    # answers per card the three things a one-line brief cannot carry (what
    # it is configured with, what it refuses, what it costs).
    ("tool.web-", "prebuilt-tools.md", "the prebuilt tools"),
    ("tool.email-send", "prebuilt-tools.md", "the prebuilt tools"),
    ("tool.youtube-transcript", "prebuilt-tools.md", "the prebuilt tools"),
    ("tool.reddit-search", "prebuilt-tools.md", "the prebuilt tools"),
    ("tool.session-identity", "prebuilt-tools.md", "the prebuilt tools"),
    # Workflow-scoped: the `chinook-assistant` package's own tools, covered
    # on that page as the demo package's, said plainly, rather than left on
    # the CLI door — `openstategraph nodes` cannot print a type the install
    # does not carry.
    ("tool.chinook-", "prebuilt-tools.md", "the demo package's tools"),
    ("guard.policy", "prebuilt-tools.md", "the Guardrail"),
    ("tool.platform-", "mcp.md", "the platform's own tools"),
    ("tool.validate-workflow", "mcp.md", "the platform's own tools"),
    ("route.grader", "evaluation.md", "grading"),
    ("route.check", "on-the-canvas.md", "the Check router"),
    ("route.", "patterns.md", "routing patterns"),
    ("guard.check", "on-the-canvas.md", "the guard on a path"),
    ("orchestrate.", "patterns.md", "orchestrator/worker"),
    ("human.approval", "patterns.md", "approval in the loop"),
    ("agent.llm", "on-the-canvas.md", "on the canvas"),
    ("function.", "on-the-canvas.md", "on the canvas"),
    ("input.skill", "ports-and-edges.md", "the skill layer"),
    ("input.markdown", "ports-and-edges.md", "the skill layer"),
    ("input.text", "on-the-canvas.md", "on the canvas"),
    ("memory.", "on-the-canvas.md", "on the canvas"),
    ("resolve.", "on-the-canvas.md", "resolving before the model"),
    ("output.", "on-the-canvas.md", "on the canvas"),
    ("workflow.subgraph", "export-and-portability.md", "mounts and portability"),
    ("annotate.", "on-the-canvas.md", "on the canvas"),
)


# --------------------------------------------------------------------------
# the data
# --------------------------------------------------------------------------


def node_types() -> list[dict]:
    """Every built-in node type, from the generated port catalogue."""
    return json.loads(PORT_SPECS.read_text(encoding="utf-8"))["node_types"]


def providers() -> list[str]:
    """The bundled `ProviderSpec` labels, from the registry itself."""
    sys.path.insert(0, str(BACKEND))
    from openstategraph.providers import builtin_specs

    return [spec.label or spec.name for spec in builtin_specs()]


def cli_verbs() -> list[str]:
    """Top-level verbs the real argparse accepts — never a list typed here."""
    import argparse as _argparse

    sys.path.insert(0, str(BACKEND))
    from openstategraph import cli

    for action in cli.build_parser()._actions:
        if isinstance(action, _argparse._SubParsersAction):
            return sorted(action.choices)
    raise AssertionError("the CLI parser has no subcommands")


def mcp_tools() -> list[str]:
    """`@server.tool(name="…")`, read as text.

    Deliberately not by importing `mcp_server`: that needs the `[mcp]` extra,
    and a documentation generator that only runs on a machine with an optional
    dependency installed is a generator that stops being run.
    """
    source = (PACKAGE / "mcp_server.py").read_text(encoding="utf-8")
    return sorted(set(re.findall(r'@server\.tool\(name="([a-z_]+)"', source)))


def agent_skills() -> list[str]:
    return sorted(p.name for p in (PACKAGE / "agent_skills").iterdir() if p.is_dir())


def _index(relative: str, key: str) -> list:
    return json.loads((PACKAGE / relative).read_text(encoding="utf-8"))[key]


def deeper_link_targets() -> list[str]:
    return sorted({target for _, target, _ in DEEPER})


# --------------------------------------------------------------------------
# rendering
# --------------------------------------------------------------------------


def deeper_for(type_id: str) -> str:
    for prefix, target, label in DEEPER:
        if type_id == prefix or (prefix.endswith(("-", ".")) and type_id.startswith(prefix)):
            return f"[{label}]({target})"
    return f"`openstategraph nodes {type_id}`"


def _cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def _table(rows: list[dict]) -> list[str]:
    out = [
        "| Type | Name | What it does | Read more |",
        "| --- | --- | --- | --- |",
    ]
    for node in rows:
        mark = " †" if node.get("scope") == "workflow" else ""
        out.append(
            f"| `{node['type']}`{mark} | {_cell(node['label'])} "
            f"| {_cell(node['description'])} | {deeper_for(node['type'])} |"
        )
    return out


def render() -> str:
    types = node_types()
    by_category: dict[str, list[dict]] = {}
    for node in types:
        by_category.setdefault(node["category"], []).append(node)
    for rows in by_category.values():
        rows.sort(key=lambda n: n["type"])

    unknown = set(by_category) - {name for name, _, _ in CATEGORIES}
    if unknown:
        raise SystemExit(
            f"port_specs.json carries categories this generator has no section for: "
            f"{sorted(unknown)} — add one to CATEGORIES in {pathlib.Path(__file__).name}"
        )

    tally = " · ".join(
        f"{name} {len(by_category.get(name, []))}" for name, _, _ in CATEGORIES
    )
    workflow_scoped = [n["type"] for n in types if n.get("scope") == "workflow"]

    lines: list[str] = [
        STAMP,
        "",
        "# Every built-in module",
        "",
        f"This install ships **{len(types)} node types** — the cards you can drop on a",
        "canvas — plus providers, CLI verbs, MCP tools, agent skills, worked examples",
        "and scaffolding templates. This page is the index: one line on each, and a",
        "link to the page that goes deeper where one exists.",
        "",
        "Nothing here is typed by hand. Every row is read out of the data the editor",
        "and the compiler already use, by `scripts/build_module_index.py`, so a type",
        "added, removed or re-described on Monday cannot leave this page telling you",
        "otherwise on Tuesday. If you would rather have it in your terminal,",
        "`openstategraph nodes` prints the same briefs, and `openstategraph nodes",
        "<type>` adds that card's fields and ports.",
        "",
        "## The node vocabulary",
        "",
        f"**{len(types)} types**, by the category the editor's palette groups them under:",
        f"{tally}.",
        "",
        (
            "A card is a *kind of step*. You configure one — a model, a sentence of "
            "rules, an allowlist — rather than writing a class for it; that is the "
            "whole bargain of this product. Drawing them and wiring them is "
            "[on the canvas](on-the-canvas.md); what the wires mean is "
            "[ports and edges](ports-and-edges.md)."
        ),
        "",
    ]

    for name, heading, blurb in CATEGORIES:
        rows = by_category.get(name, [])
        if not rows:
            continue
        lines += [f"### {heading} ({len(rows)})", "", blurb, "", *_table(rows), ""]

    lines += [
        f"† **Workflow-scoped** — {len(workflow_scoped)} of the {len(types)} "
        "(`" + "`, `".join(workflow_scoped) + "`) are contributed by a workflow",
        "package rather than by the install, so they appear only in a project that",
        "carries that package. Your own `tools/*.py` become cards the same way — see",
        "[building an atom](building-an-atom.md).",
        "",
        "## The other built-in families",
        "",
        "Each of these already has a canonical page or a command that prints it, and",
        "a second copy here would be a second thing to keep true. So: the count, from",
        "the same source the software uses, and where to read it.",
        "",
        "| Family | Count | Where its brief lives |",
        "| --- | --- | --- |",
        f"| Model providers | {len(providers())} | "
        "`openstategraph providers` — every provider, the variable it reads, and "
        "whether it is set |",
        f"| CLI verbs | {len(cli_verbs())} | [the CLI reference](cli.md) — one "
        "section each, held against the real parser |",
        f"| MCP tools | {len(mcp_tools())} | [the MCP layer](mcp.md) |",
        f"| Bundled agent skills | {len(agent_skills())} | "
        "[the OpenStateGraph skill](the-openstategraph-skill.md); `init` installs "
        "them into your project |",
        f"| Worked examples | {len(_index('examples/index.json', 'examples'))} | "
        "`openstategraph examples list`, one line each; copy one with "
        "`openstategraph examples copy <slug>` |",
        f"| `new` templates | {len(_index('templates/index.json', 'templates'))} | "
        "`openstategraph new --list-templates`. A template is a *copy* and stops "
        "existing; a mounted package is a *reference* |",
        "",
        "## When this page is wrong",
        "",
        "It cannot be, quietly. `backend/tests/test_documented_modules_match_the_vocabulary.py`",
        "renders the page afresh and compares it byte for byte, so a type with no row,",
        "a row with no type, and a description that has moved are all one red test.",
        "Regenerate with:",
        "",
        "```bash",
        "python3 scripts/build_module_index.py --write",
        "```",
        "",
    ]
    return "\n".join(lines)


def first_difference(committed: str, rendered: str) -> str:
    """A readable excerpt, because a row nobody can open is not a signal."""
    diff = list(
        difflib.unified_diff(
            committed.splitlines(),
            rendered.splitlines(),
            "docs/modules.md (committed)",
            "docs/modules.md (from the data)",
            lineterm="",
            n=1,
        )
    )
    return "\n".join(diff[:40]) or "(no textual difference — trailing bytes?)"


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate docs/modules.md")
    parser.add_argument("--check", action="store_true", help="fail if the page is stale")
    parser.add_argument("--write", action="store_true", help="rewrite the page (default)")
    args = parser.parse_args()

    rendered = render()
    if args.check:
        committed = PAGE.read_text(encoding="utf-8") if PAGE.exists() else ""
        if committed != rendered:
            print(first_difference(committed, rendered), file=sys.stderr)
            print(
                "docs/modules.md is out of date — "
                "run python3 scripts/build_module_index.py --write",
                file=sys.stderr,
            )
            return 1
        print(f"docs/modules.md is current ({len(node_types())} node types)")
        return 0

    PAGE.write_text(rendered, encoding="utf-8")
    print(f"wrote docs/modules.md ({len(node_types())} node types, {len(rendered):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
