#!/usr/bin/env python3
"""Publish the gap report's field contract as TypeScript for the report door.

    python3 scripts/generate_gap_report_ts.py --write
    python3 scripts/generate_gap_report_ts.py --check

`team-board-and-gap-reports/09`. The door that accepts a report is a Deno
function and cannot import a Pydantic model, so it needs the allowlist in its
own language. The one thing it must not have is a *second* description of the
report — a hand-written list of field names in TypeScript would be exactly the
drift `docs/gap-report.schema.json` exists to prevent, one language further
away from the model.

So this script derives the contract from `gap_report.gap_report_schema()`, the
same single implementation `generate_gap_report_schema.py` publishes the JSON
Schema from, and `--check` is the drift gate: a field added to the model and
not regenerated here is a red test, not a door that silently drops it.

What is generated is the *vocabulary* — which fields exist, which are
required, which enum values each accepts, how long a carried sentence may be.
The validating code is hand-written beside it, because a validator generated
from a schema is a schema library, and this door deliberately has no
dependencies at all.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "backend"))

from openstategraph.gap_report import (  # noqa: E402
    GAP_CARD_CATEGORY,
    TEXT_CAP,
    gap_report_schema,
)
from openstategraph.kanban_store import TEAM_BOARD  # noqa: E402

#: Where the door reads it. Beside `index.ts` rather than in a shared
#: directory: this file is generated for one consumer, and a generated file
#: two things import is a file nobody dares regenerate.
CONTRACT_PATH = (
    Path(__file__).resolve().parents[1]
    / "supabase"
    / "functions"
    / "gap-report"
    / "contract.generated.ts"
)

HEADER = """// Generated by scripts/generate_gap_report_ts.py from
// openstategraph.gap_report.GapReport — never hand-edited, and checked by
// `python3 scripts/generate_gap_report_ts.py --check`.
//
// The report's vocabulary, in the door's own language: which fields a report
// may carry, which it must carry, which values each enum accepts, how long a
// carried sentence may be, and which board a filed report lands on. The
// validator that consumes this is hand-written in `index.ts`
// (team-board-and-gap-reports/09, `17`).
"""


def _definition(schema: dict[str, Any], ref: str) -> dict[str, Any]:
    return schema["$defs"][ref.rsplit("/", 1)[-1]]


def field_shapes(schema: dict[str, Any]) -> dict[str, dict[str, Any]]:
    """Each property, as the four shapes the door knows how to check.

    Derived rather than listed, so a field whose type changes in the model
    changes here too. An unrecognised shape raises — a door that guessed would
    be a door that let a new shape through unchecked.
    """
    shapes: dict[str, dict[str, Any]] = {}
    for name, spec in schema["properties"].items():
        if "$ref" in spec:
            defined = _definition(schema, spec["$ref"])
            if "enum" in defined:
                shapes[name] = {"kind": "enum", "values": list(defined["enum"])}
                continue
            if defined.get("type") == "object":
                shapes[name] = {"kind": "refusal"}
                continue
        elif spec.get("type") == "string":
            shapes[name] = {"kind": "string"}
            continue
        elif spec.get("type") == "array":
            shapes[name] = {"kind": "stringArray"}
            continue
        elif [option.get("type") for option in spec.get("anyOf", ())] == [
            "string",
            "null",
        ]:
            shapes[name] = {"kind": "nullableString"}
            continue
        else:
            raise SystemExit(f"{name!r} has a shape this generator cannot express")
    return shapes


def contract() -> dict[str, Any]:
    schema = gap_report_schema()
    refusal = _definition(schema, "#/$defs/Refusal")
    sources = _definition(schema, refusal["properties"]["source"]["$ref"])
    return {
        "fields": field_shapes(schema),
        "required": list(schema["required"]),
        "refusalFields": list(refusal["properties"]),
        "refusalRequired": list(refusal["required"]),
        "refusalSources": list(sources["enum"]),
        "textCap": TEXT_CAP,
        # `team-board-and-gap-reports/17`. Where a filed report lands, and
        # what it is once it has. The door does not choose either — the
        # database routine is the single writer, for the atomicity argument
        # `0003` records — but it must not spell them in its own language
        # either: a log line naming a board the row is not on is how the
        # first live report came to sit where no tab could list it. So the
        # two words are published here, from the constants the board and the
        # report already own, and the migration's column default is pinned
        # against them by
        # `test_the_keyless_door_files_onto_a_board_a_tab_reads.py`.
        "board": TEAM_BOARD,
        "category": GAP_CARD_CATEGORY,
    }


def rendered() -> str:
    body = json.dumps(contract(), indent=2, sort_keys=True)
    return f"{HEADER}\nexport const CONTRACT = {body} as const;\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the committed contract is not what the model produces",
    )
    parser.add_argument(
        "--write", action="store_true", help="write the contract (the default)"
    )
    arguments = parser.parse_args(argv)

    wanted = rendered()
    if arguments.check:
        found = (
            CONTRACT_PATH.read_text(encoding="utf-8") if CONTRACT_PATH.exists() else ""
        )
        if found == wanted:
            print(f"{CONTRACT_PATH} is current")
            return 0
        print(
            f"{CONTRACT_PATH} is stale — run "
            "`python3 scripts/generate_gap_report_ts.py --write`",
            file=sys.stderr,
        )
        return 1

    CONTRACT_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONTRACT_PATH.write_text(wanted, encoding="utf-8")
    print(f"wrote {CONTRACT_PATH}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
