#!/usr/bin/env python3
"""Publishes `generated_module_contract.CLAUSES` as the skill's reference page.

`skills/atom-forge/` is plain markdown and agent-agnostic on purpose — it must
work for an agent that cannot import Python. So the contract is *published*
here rather than restated, the same relationship `docs/openapi.json` has with
Pydantic: one source of truth, one generated and committed publication, and a
drift test that fails when they disagree.

Run: ``python3 scripts/render_generated_module_contract.py``
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from openstategraph.generated_module_contract import CLAUSES  # noqa: E402

TARGET = ROOT / "skills" / "atom-forge" / "references" / "generated-module-contract.md"

HEADER = """<!-- GENERATED by scripts/render_generated_module_contract.py — do not hand-edit.
     Source of truth: backend/openstategraph/generated_module_contract.py -->

# The generated-module contract

**What a module built through this skill must be, and what checks it.**

`every-workflow-green` 34. A run that finds nothing in the library for what it
was asked offers to build one; this is the shape the thing that comes back has
to have. The clauses below are not advice — `check_generated_module()` reads a
candidate module with `ast` and returns a violation for each one it breaks, and
the interview is not finished while any violation stands.

Every clause names the symbols in **this installation** it depends on, and a
test resolves each of them. That gate exists because the clause this file
replaced named `ToolRuntime` — a LangChain seam this platform does not surface
— and seven green tests never noticed, because all of them asked whether the
words were present rather than whether the thing existed. *Do not promise which
is not possible* binds the checklist as hard as it binds the build.

What a tool can actually reach here: its node's config through
`configure(data)`, the run through `langgraph.config.get_config()`, memory
through `get_store()`, and **graph state not at all** — `BaseTool.run`
validates `**kwargs` into `Args` and calls `_execute(args)`. A design that
needs graph state belongs in a node, not a tool.

---
"""

FOOTER = """
---

## What the checker cannot see

It reads the module with `ast` and never imports it — discovery imports a
workflow's `tools/` and records that as a known risk, and a gate that must
execute what it is gating is not a gate. So a class that subclasses `BaseTool`
through an alias, or a `data` key assembled at run time, is invisible to it.
The fix is the same one `test_data_key_contract` asks for: keep the key a
string literal at the point of use.

Passing every clause is necessary and not sufficient. The module's own
behaviour tests are extra — and they are never the gate, because an agent that
writes its own tests writes tests it passes.
"""


def render() -> str:
    parts = [HEADER]
    for index, clause in enumerate(CLAUSES, start=1):
        parts.append(
            f"\n## {index}. `{clause.id}`\n\n"
            f"**The rule, in the words the developer is handed:**\n\n"
            f"> {clause.rule}\n\n"
            f"**Why:** {clause.why}\n\n"
            f"**Seams it depends on:** "
            + (", ".join(f"`{symbol}`" for symbol in clause.seam) or "_none_")
            + "\n"
        )
    parts.append(FOOTER)
    return "".join(parts)


if __name__ == "__main__":
    TARGET.write_text(render())
    print(f"wrote {TARGET.relative_to(ROOT)}")
