#!/usr/bin/env python3
"""Publishes `graderVerdictLine` into `/chat`'s dependency-free page.

`production-ready` 94. One judgement — the grader's verdict on a candidate
awaiting approval — reaches a reviewer through two doors: the editor's approval
card, which imports `src/view/ask/graderVerdictLine.ts`, and `/chat`'s approval
box, which imports nothing on purpose. Until this script the second door was a
hand-kept ternary restating the same rules in JavaScript, and it had **already**
drifted: a verdict of `"  "` printed the bare reason there and nothing in the
editor, and neither side trimmed the same fields.

Option 2 of the ticket, and the same relationship `docs/openapi.json` has with
Pydantic and `generated-module-contract.md` has with `CLAUSES`: one source of
truth, one generated and committed publication, and a drift test that fails
when they disagree. Option 1 (build the sentence server-side and put it on the
`interrupt` frame) was rejected because it makes the wire carry English, which
is a contract decision and is filed as `production-ready/103`. Option 3 (keep
two spellings, pin them with a shared case table) was rejected because it
leaves the knowledge duplicated and only *reports* the drift after someone
writes it — the parity table it proposes is kept anyway, in
`graderVerdictLine.parity.test.ts`, as the check on this generation.

Run: ``python3 scripts/render_grader_verdict_line.py``
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "view" / "ask" / "graderVerdictLine.ts"
TARGET = ROOT / "backend" / "openstategraph" / "api" / "static" / "chat.html"

SOURCE_BEGIN = "// GENERATED-SOURCE-BEGIN graderVerdictLine"
SOURCE_END = "// GENERATED-SOURCE-END graderVerdictLine"
TARGET_BEGIN = "// GENERATED-BEGIN graderVerdictLine"
TARGET_END = "// GENERATED-END graderVerdictLine"

#: The one line of the region that is not already JavaScript.
TYPED_SIGNATURE = "export function graderVerdictLine(approval: GraderApproval): string {"
PLAIN_SIGNATURE = "function graderVerdictLine(approval) {"

BANNER = (
    "// GENERATED by scripts/render_grader_verdict_line.py — do not hand-edit.\n"
    "  // Source of truth: src/view/ask/graderVerdictLine.ts (`production-ready` 94).\n"
    "  // The editor's approval card and this page are two doors onto one\n"
    "  // judgement; this is that judgement's only spelling. Edit the TypeScript\n"
    "  // and re-run the script — `backend/tests/test_one_graders_sentence.py`\n"
    "  // fails while the two disagree, and `graderVerdictLine.parity.test.ts`\n"
    "  // runs both over the same table of cases."
)


def _region(text: str, begin: str, end: str) -> tuple[int, int]:
    start = text.index(begin) + len(begin)
    stop = text.index(end, start)
    return start, stop


def render() -> str:
    """The JavaScript body, indented for `chat.html`'s single script block."""
    source = SOURCE.read_text(encoding="utf-8")
    start, stop = _region(source, SOURCE_BEGIN, SOURCE_END)
    lines = source[start:stop].strip("\n").split("\n")
    if TYPED_SIGNATURE not in lines:
        raise SystemExit(
            f"{SOURCE.name}: the generated region no longer opens with the signature "
            f"this script knows how to untype:\n  {TYPED_SIGNATURE}"
        )
    lines[lines.index(TYPED_SIGNATURE)] = PLAIN_SIGNATURE
    for line in lines:
        # The region is copied verbatim, so anything TypeScript-only in it
        # would reach the browser as a syntax error and take the whole page
        # with it. Only the signature is rewritten; the rest must already be
        # JavaScript.
        if line.strip().startswith("//"):
            continue
        if ": string" in line or ": number" in line or " as " in line:
            raise SystemExit(f"{SOURCE.name}: TypeScript syntax inside the region: {line!r}")
    body = "\n".join(("  " + line if line else line) for line in lines)
    return f"  {BANNER}\n{body}\n  "


def main() -> int:
    page = TARGET.read_text(encoding="utf-8")
    start, stop = _region(page, TARGET_BEGIN, TARGET_END)
    updated = page[:start] + "\n" + render() + page[stop:]
    if updated != page:
        TARGET.write_text(updated, encoding="utf-8")
        print(f"wrote {TARGET.relative_to(ROOT)}")
    else:
        print("up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
