#!/usr/bin/env python3
"""Stamp every generated wiki page with the commit and date it came from.

`docs-and-gaps/27`. The OpenWiki pages under `openwiki/` are days or weeks
behind the tree at any given moment, and that is structural rather than
careless: `CLAUDE.md` records that "let OpenWiki regenerate" means *a human
runs it locally*, because the scheduled workflow has never produced a page —
it needs an `OPENAI_API_KEY` in the repository's secrets and there is none.
(The variable, never a value. Nothing here reads a key and nothing here should.)

Staleness was never the complaint. The complaint was that **nothing on the page
said so**. `openwiki/.last-update.json` holds the commit and the timestamp of
the last run, and it is a dotfile a reader has no reason to open, so a
contributor reading `how-to/extending.md` had no way to tell a current page
from a nine-day-old one. This script copies those two values onto the pages
themselves.

## It does not survive a refresh, and that is the design

The generator writes each page whole, so it deletes these stamps. Nothing can
be done about that from here — we do not own the generator — and pretending
otherwise would produce a stamp that quietly disappears. So the stamp is
*expected* to disappear, exactly when it becomes wrong anyway (a refresh names
a new commit), and
`backend/tests/test_a_generated_wiki_page_says_when_it_was_generated.py` turns
the disappearance into a red test naming every unstamped page. The remedy is
one line, and it is printed in the failure message:

    python3 scripts/stamp_wiki_freshness.py

Run it after every `openwiki code --update`.

## What it writes, and what it refuses to write

The stamp carries the short sha, the date, and the command that refreshes the
page. It carries **no arithmetic** — not "nine days stale", not "three hundred
commits behind" — because either number is wrong on the next commit, which is
the failure this repository has recorded more often than any other. It names
the commit and hands the reader `git log <sha>..HEAD`; the subtraction is the
reader's and is correct whenever it is done.

It also does not restate *why* the scheduled job has not run. That fact has one
home, in `CLAUDE.md`'s OpenWiki block, where it has already been corrected
twice; a second spelling of it on fifteen pages would be fifteen more places
for the third correction to miss. The stamp defers instead.

Idempotent: re-running replaces the block rather than adding a second one.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
WIKI = REPO / "openwiki"
LAST_UPDATE = WIKI / ".last-update.json"

START = "<!-- FRESHNESS:START -->"
END = "<!-- FRESHNESS:END -->"

#: `INSTRUCTIONS.md` is the brief handed *to* OpenWiki — hand-written input, not
#: output, never overwritten by a run. It has no generation to stamp.
NOT_GENERATED = {"INSTRUCTIONS.md"}


def _stamp(head: str, date: str) -> str:
    return (
        f"{START}\n"
        f"> **Generated by OpenWiki from `{head}` on {date}.** Anything committed since\n"
        f"> then is not reflected on this page — `git log {head}..HEAD` is the difference.\n"
        "> Refreshing it means running `openwiki code --update` in a checkout;\n"
        "> `CLAUDE.md`'s OpenWiki note records why the scheduled job has not done it.\n"
        "> This block is written by `scripts/stamp_wiki_freshness.py` and not by the\n"
        "> generator, so a refresh removes it and the wiki-freshness test asks for it back.\n"
        f"{END}\n"
    )


def _strip_existing(text: str) -> str:
    """Remove a previous block, so re-running replaces rather than stacks."""
    if START not in text or END not in text:
        return text
    before, rest = text.split(START, 1)
    after = rest.split(END, 1)[1]
    return before + after.lstrip("\n")


def _insert(text: str, stamp: str) -> str:
    """Below the front matter if there is any, at the very top if there is not.

    A markdown blockquote inside a `---` block is not YAML, and four of these
    pages have front matter the site reads.
    """
    if text.startswith("---\n"):
        closing = text.index("\n---\n", 3) + len("\n---\n")
        return text[:closing] + "\n" + stamp + "\n" + text[closing:].lstrip("\n")
    return stamp + "\n" + text.lstrip("\n")


def main() -> int:
    if not LAST_UPDATE.is_file():
        print(f"no {LAST_UPDATE.relative_to(REPO)} — has OpenWiki ever run here?")
        return 1
    recorded = json.loads(LAST_UPDATE.read_text(encoding="utf-8"))
    head, date = recorded["gitHead"][:7], recorded["updatedAt"][:10]
    stamp = _stamp(head, date)

    changed = 0
    for page in sorted(WIKI.rglob("*.md")):
        if page.relative_to(WIKI).as_posix() in NOT_GENERATED:
            continue
        text = page.read_text(encoding="utf-8")
        stamped = _insert(_strip_existing(text), stamp)
        if stamped != text:
            page.write_text(stamped, encoding="utf-8")
            changed += 1
            print(f"stamped {page.relative_to(REPO)}")
    print(f"{changed} page(s) stamped from {head} ({date})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
