"""Second-brain builders: ``IKnowledgeBuilder`` → ``BaseKnowledgeBuilder`` → concretes.

The *builders* are the open extension point of the knowledge layer — the
store and the lookup tool (``knowledge.py``, ``prebuilt_knowledge.py``) stay
exactly one store and one tool regardless of which builder wrote a doc. A
topic is a topic: once ``knowledge/<topic>.md`` exists, nothing downstream
knows or cares which source produced it. The files are plain Markdown in
git, read both by workflow agents at runtime (through the lookup tool) and
by any coding agent opening ``workflows/<slug>/knowledge/*.md`` directly.

A builder answers two questions:

- ``discover(workflow_dir, document, workflows_root)`` — which topics does
  this workflow have, from *my* kind of source? Each topic carries its own
  **brief**: the raw source material (a schema, a directory tree, a spec
  fragment) the model turns into a procedural doc. Discovery also reports
  **warnings** — a source it recognized but could not open (a missing
  optional driver) is reported, never silently dropped and never a crash.
- ``build(topic, model)`` — one model call, composed by the base: the shared
  write-a-procedural-doc instruction plus the topic's brief.

The base owns everything shared — prompt composition, the model invocation,
the generated-marker header, and the write-with-regeneration-policy — so a
new source is *only* a ``discover`` implementation registered in
``BUILDERS``. Never edit the endpoint to add a source.

**Regeneration policy** (invariant 5 of the knowledge architecture): the
marker line records the *owning builder* (``source=<kind>``). ``owns()``
gates regeneration three ways —

- no marker → hand-authored, never touched, reported as skipped;
- marker naming *this* builder (or the legacy marker with no source, from
  docs written before ownership was recorded) → owned, regenerated;
- marker naming a *different* builder → a cross-builder topic collision,
  **refused and reported**, never last-write-wins.

Hand-tuning a generated doc is therefore one deliberate act: delete the
marker line and the file is yours.

**Every generated doc opens with its index line** — a one-sentence summary
right after the marker — because ``PackageKnowledge.topics()`` serves the
first meaningful line of each doc as the free index tier: authoring the doc
authors the index.
"""

from __future__ import annotations

import hashlib
import json
import re
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, ClassVar, Protocol, runtime_checkable

from openstategraph.knowledge import BaseKnowledge
from openstategraph.knowledge_engines import ENGINE_ADAPTERS, recognize

#: First line prefix of every builder-owned doc. Its absence marks a file as
#: hand-authored and untouchable — see the module docstring's policy.
GENERATED_MARKER = "<!-- generated by build-second-brain"

_MARKER_SOURCE_RE = re.compile(r"source=([a-z0-9-]+)")
_MARKER_HASH_RE = re.compile(r"hash=([0-9a-f]{12})")
#: The claim-time hash record on a claimed (hand-owned) doc: a trailing HTML
#: comment, chosen over a sidecar file as the least-invasive spelling — the
#: doc stays one self-contained file in git, and Markdown renderers hide it.
CLAIMED_HASH_COMMENT = "<!-- knowledge-claimed source-hash="
_CLAIMED_HASH_RE = re.compile(
    re.escape(CLAIMED_HASH_COMMENT) + r"([0-9a-f]{12}) -->"
)


def source_hash(brief: str) -> str:
    """A short content hash of a topic's introspection input (its brief).

    Stamped into the generated marker at build time and recorded on claimed
    docs at claim time; the curation list compares it against the current
    source's recomputed hash to badge staleness ("the source behind this doc
    changed") — you keep the pen; you lose the ignorance.
    """
    return hashlib.sha256(brief.encode()).hexdigest()[:12]


def marker_hash(text: str) -> str | None:
    """The source hash a generated doc's marker stamped, if any."""
    if not text.startswith(GENERATED_MARKER):
        return None
    match = _MARKER_HASH_RE.search(text.splitlines()[0])
    return match.group(1) if match else None


def claimed_hash(text: str) -> str | None:
    """The claim-time source hash a claimed doc's trailing comment records."""
    match = _CLAIMED_HASH_RE.search(text)
    return match.group(1) if match else None

#: The node types whose config names a SQL database, and the bundled default
#: the chinook-* family is hard-wired to.
_SQL_NODE_PREFIX = "tool.sql-"
_CHINOOK_NODE_PREFIX = "tool.chinook-"
_CHINOOK_DATABASE = "chinook-assistant/data/Chinook_Sqlite.sqlite"

#: The node types that mount another workflow as a child. Their
#: ``data.workflow`` slugs ARE ``RootKnowledgeBuilder``'s topics — a parent
#: writes a routing doc for what it can actually route to, and nothing else.
_MOUNT_NODE_TYPES = ("workflow.subgraph", "team.workflow")

#: The node types that make **the project** a source. A workflow wiring these
#: can enumerate and describe every package on the platform at run time, so
#: the project is a thing it reads — recognised from the wiring exactly as a
#: database is recognised from a ``tool.sql-*`` node's connection field.
_PROJECT_NODE_TYPES = (
    "tool.platform-list-workflows",
    "tool.platform-describe-workflow",
)


def marker_source(text: str) -> str | None:
    """The owning builder a doc's marker records.

    None → no marker, hand-authored. ``""`` → the legacy marker written
    before ownership was recorded (owned by whichever builder claims the
    topic). Otherwise the ``source=<kind>`` of the owning builder.
    """
    if not text.startswith(GENERATED_MARKER):
        return None
    first_line = text.splitlines()[0]
    match = _MARKER_SOURCE_RE.search(first_line)
    return match.group(1) if match else ""


@dataclass(frozen=True)
class KnowledgeTopic:
    """One buildable topic: its name and the source material for the model."""

    name: str
    brief: str
    #: What the builder actually looked at (tables/files/tools) — becomes the
    #: doc's provenance footer, so a wrong claim is auditable to its source.
    provenance: tuple[str, ...] = ()


@dataclass(frozen=True)
class Discovery:
    """What one builder found in one workflow: topics, plus the sources it
    recognized but could not open (reported, never a crash)."""

    topics: list[KnowledgeTopic] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


@runtime_checkable
class IKnowledgeBuilder(Protocol):
    """The contract the build endpoint depends on — a shape, not a class."""

    source_kind: str

    def discover(
        self, workflow_dir: Path, document: dict[str, Any], workflows_root: Path
    ) -> Discovery: ...

    def build(self, topic: KnowledgeTopic, model: Any) -> str: ...


class BaseKnowledgeBuilder(ABC):
    """Shared machinery: prompt composition, model call, marker, writing.

    A concrete supplies ``source_kind`` and ``discover``; everything else —
    including the regeneration and ownership policy — is declared once here.
    """

    source_kind: ClassVar[str]

    #: True when this builder's topics have a **recomputable brief** — i.e.
    #: ``discover`` can be re-run cheaply and deterministically to ask "does
    #: the source still hash the same?". That is what the staleness badge
    #: needs, and it is a property of the builder, not a list the curation
    #: module keeps: `knowledge_curation` used to name `SqlKnowledgeBuilder`
    #: and `RootKnowledgeBuilder` literally, so a *registered* mechanical
    #: builder — a plugin's, or this module's own next one — silently got no
    #: stale badges at all. Agentic builders set this False (no brief to
    #: recompute; unknown is not stale).
    mechanical: ClassVar[bool] = True

    #: The shared instruction. The topic's brief is context; this is the
    #: task. Concretes never restate it (they may override it wholesale when
    #: their docs are a different genre — see ``RootKnowledgeBuilder``).
    INSTRUCTION = (
        "Write a concise procedural knowledge document for the topic below, "
        "for an AI agent that will use this source at runtime. The VERY "
        "FIRST line of your answer must be a single-sentence summary of the "
        "topic ('<topic> — <what it is and what questions it answers>'); "
        "this line becomes the topic's entry in the knowledge index. Then "
        "the document: infer and state the business meaning; explain each "
        "column or member's semantics; spell out the JOIN rules / "
        "relationships explicitly; note caveats (nullable fields, units, "
        "encodings, gotchas visible in the sample). Markdown, no preamble, "
        "no code fences around the whole answer."
    )

    @abstractmethod
    def discover(
        self, workflow_dir: Path, document: dict[str, Any], workflows_root: Path
    ) -> Discovery:
        """Every topic this builder can write for this workflow, plus
        warnings for recognized-but-unavailable sources."""

    def compose_prompt(self, topic: KnowledgeTopic) -> str:
        return f"{self.INSTRUCTION}\n\n# Topic: {topic.name}\n\n{topic.brief}"

    def build(self, topic: KnowledgeTopic, model: Any) -> str:
        """One model call → the doc body. The write is `write()`'s job."""
        response = model.invoke(self.compose_prompt(topic))
        return str(getattr(response, "content", response)).strip()

    def marker_header(self, topic: KnowledgeTopic | None = None) -> str:
        """The marker line: this builder as owner, plus the source content
        hash (of the topic's brief) the staleness badge compares against.
        Agentic builders have no recomputable brief, so no hash is stamped."""
        stamp = f" hash={source_hash(topic.brief)}" if topic is not None and topic.brief else ""
        return (
            f"{GENERATED_MARKER} source={self.source_kind}{stamp}; regenerate via "
            "POST /api/workflows/<slug>/knowledge/build; delete this line to "
            "claim the file as hand-authored -->"
        )

    def target_path(self, workflow_dir: Path, topic: KnowledgeTopic) -> Path:
        return workflow_dir / "knowledge" / f"{BaseKnowledge.normalize(topic.name)}.md"

    def owns(self, workflow_dir: Path, topic: KnowledgeTopic) -> bool:
        """May this builder (re)generate this topic's file?

        True for an absent file, a marker naming this builder, or the legacy
        marker with no source. False for a hand-authored file (no marker)
        AND for a marker naming a different builder — use ``collides_with``
        to tell the two refusals apart.
        """
        path = self.target_path(workflow_dir, topic)
        if not path.is_file():
            return True
        owner = marker_source(path.read_text())
        return owner in ("", self.source_kind)

    def collides_with(self, workflow_dir: Path, topic: KnowledgeTopic) -> str | None:
        """The *other* builder that owns this topic's file, if any."""
        path = self.target_path(workflow_dir, topic)
        if not path.is_file():
            return None
        owner = marker_source(path.read_text())
        if owner is None or owner in ("", self.source_kind):
            return None
        return owner

    def write(self, workflow_dir: Path, topic: KnowledgeTopic, body: str) -> bool:
        """Writes ``knowledge/<topic>.md``; False means not owned, kept.

        The body's first line is the doc's index line (the drafting
        instruction demands it), so the layout is marker, blank line, body —
        no injected heading between the marker and the index line.
        """
        if not self.owns(workflow_dir, topic):
            return False
        path = self.target_path(workflow_dir, topic)
        path.parent.mkdir(parents=True, exist_ok=True)
        footer = ""
        if topic.provenance:
            footer = (
                "\n\n---\n_Provenance: built from "
                + "; ".join(topic.provenance)
                + "._"
            )
        path.write_text(f"{self.marker_header(topic)}\n\n{body}{footer}\n")
        return True


# ---------------------------------------------------------------------------
# SQL — one topic per table, generic over engines via the adapter seam.
# ---------------------------------------------------------------------------


def sql_sources_in_document(
    document: dict[str, Any], workflows_root: Path
) -> list[tuple[str, str]]:
    """Every recognized SQL source in the document, as ``(ref, engine)``.

    Recognition reads the wiring (``knowledge_engines.recognize``): a bare
    path is SQLite (jailed to the workflows root, must exist; the ref is
    normalized to root-relative), a ``postgres://``/``mssql://`` URL names
    its engine and is passed through for the adapter to open.
    """
    root = workflows_root.resolve()
    found: list[tuple[str, str]] = []
    seen: set[str] = set()
    for node in document.get("nodes") or []:
        node_type = str(node.get("type") or "")
        ref = ""
        if node_type.startswith(_SQL_NODE_PREFIX):
            ref = str((node.get("data") or {}).get("database") or "").strip()
        elif node_type.startswith(_CHINOOK_NODE_PREFIX):
            ref = _CHINOOK_DATABASE
        if not ref:
            continue
        engine = recognize(ref)
        if engine is None:
            continue
        if engine == "sqlite" and "://" not in ref:
            candidate = (root / ref).resolve()
            try:
                candidate.relative_to(root)
            except ValueError:
                continue
            if not candidate.is_file():
                continue
            ref = str(candidate.relative_to(root))
        if ref in seen:
            continue
        seen.add(ref)
        found.append((ref, engine))
    return found


class SqlKnowledgeBuilder(BaseKnowledgeBuilder):
    """One topic per table of every SQL source the workflow's tools use.

    Engines are the adapter seam's business (``knowledge_engines``): this
    builder recognizes refs from the wiring, asks the matching adapter for
    tables and briefs, and reports a recognized source whose driver is
    missing as a warning — never a crash, never a silent skip.
    """

    source_kind = "sql"

    def discover(
        self, workflow_dir: Path, document: dict[str, Any], workflows_root: Path
    ) -> Discovery:
        root = workflows_root.resolve()
        topics: list[KnowledgeTopic] = []
        warnings: list[str] = []
        seen: set[str] = set()
        for ref, engine in sql_sources_in_document(document, workflows_root):
            adapter = ENGINE_ADAPTERS[engine]
            usable, warning = adapter.available()
            if not usable:
                warnings.append(
                    f"{ref}: recognized as {engine}, but unavailable — {warning}"
                )
                continue
            connection_ref = str(root / ref) if engine == "sqlite" else ref
            for table in adapter.list_tables(connection_ref):
                key = BaseKnowledge.normalize(table)
                if key in seen:
                    continue  # same-named table in a second source: first wins
                seen.add(key)
                topics.append(
                    KnowledgeTopic(
                        name=table,
                        brief=adapter.table_brief(connection_ref, table),
                        provenance=(f"table {table} of {ref} ({engine} schema + sample)",),
                    )
                )
        return Discovery(topics=topics, warnings=warnings)


# ---------------------------------------------------------------------------
# Pointer builders — one coarse doc per *other workflow*, never a copy of it.
# ---------------------------------------------------------------------------


class AbstractWorkflowPointerBuilder(BaseKnowledgeBuilder):
    """Shared machinery for builders whose topics are **other workflows**.

    Two concretes live under this: ``RootKnowledgeBuilder`` (the children this
    document *mounts*) and ``ProjectKnowledgeBuilder`` (the packages this
    document's platform tools can *see*). They share one thing and differ in
    one thing, and both matter:

    - **Shared: what a brief about a workflow is.** Name and slug, the
      topology the canvas itself declares, the head of its ``AGENTS.md``, and
      whether it has a second brain of its own. That is a genuine
      duplication-of-knowledge if written twice, and it is *within* a family
      — the CLAUDE.md boundary rule's "abstract base" case, not its
      "composition" case.
    - **Different: which workflows are topics, and what genre the doc is.**
      The subclass owns ``discover`` and ``INSTRUCTION``, and nothing else.

    The standing rule both obey: **pointers, not copies.** A doc here says
    what another workflow is and where to go for depth. It never carries that
    workflow's table-level detail upward — that recreates context bloat one
    level up and rots the moment the child rebuilds.
    """

    def workflow_brief(
        self, slug: str, name: str, workflows_root: Path, document: dict[str, Any]
    ) -> str:
        child_dir = workflows_root / slug
        parts = [f"Child workflow: {name} (slug: {slug})"]
        parts.append(self._topology(document))
        agents_md = child_dir / "AGENTS.md"
        if agents_md.is_file():
            head = "\n".join(agents_md.read_text().splitlines()[:30]).strip()
            if head:
                parts.append(f"## Description (AGENTS.md head)\n{head}")
        if any((child_dir / "knowledge").glob("*.md")):
            parts.append(
                "This child HAS its own knowledge store (a second brain) — "
                "end the doc with the drill pointer."
            )
        else:
            parts.append("This child has no knowledge store of its own.")
        return "\n\n".join(parts)

    @staticmethod
    def _topology(document: dict[str, Any]) -> str:
        """What the canvas itself says the other workflow can do — node types,
        router branches, and mounted grandchildren, mechanically derived."""
        nodes = document.get("nodes") or []
        lines = ["## Topology"]
        types = sorted({str(n.get("type") or "") for n in nodes if n.get("type")})
        if types:
            lines.append("Node types: " + ", ".join(types))
        for node in nodes:
            data = node.get("data") if isinstance(node, dict) else None
            if not isinstance(data, dict):
                continue
            raw_branches = data.get("branches")
            branches = [
                str(b.get("name") or "")
                for b in (raw_branches if isinstance(raw_branches, list) else [])
                if isinstance(b, dict)
            ]
            if branches:
                lines.append(f"Router branches: {', '.join(b for b in branches if b)}")
            if str(node.get("type") or "") in _MOUNT_NODE_TYPES and data.get("workflow"):
                lines.append(f"Mounts child workflow: {data['workflow']}")
        return "\n".join(lines)


class RootKnowledgeBuilder(AbstractWorkflowPointerBuilder):
    """Topics = the children this workflow **mounts**; docs written to route.

    **Discovery rule (ticket 16, corrected against live evidence).** The
    topics are the distinct slugs named by this document's own
    ``workflow.subgraph`` / ``team.workflow`` nodes — nothing else. A
    workflow that mounts nothing yields no topics, so the builder never
    fires on a leaf.

    The rule it replaces enumerated *every published, non-hidden workflow on
    the platform* and only used the mounts as a yes/no gate on whether to
    fire at all. That was inverted in both directions, and both were found on
    disk rather than argued: ``workflows/concierge/knowledge/`` held
    ``chinook-assistant.md`` — a routing pointer to a workflow the concierge
    does not mount and therefore cannot reach — while carrying **no** doc for
    ``workflow-architect``, a child it does mount, because that child is
    ``hidden: true`` and ``list()`` drops hidden packages. A gateway was
    being taught to route where it has no edge, and left ignorant of where it
    does.

    So: **the mount is the routing fact.** ``published``/``hidden`` describe
    a package's own visibility on the ``/chat`` surface; they say nothing
    about whether a *parent* can invoke it, because a mount compiles the
    child as a subgraph and ``document_loader`` never consults either flag.
    Ticket 04's publish gate was right for the question it was asked — "may a
    routing doc send a customer to a draft they cannot open?" — and does not
    apply once the destination is reached through a mount rather than by
    slug. A mounted slug that will not load is a **warning**, the same way an
    unopenable SQL source is: reported, never a doc, never a crash.

    Hierarchy means pointers, not copies: each doc is one coarse page — what
    the child answers, its capabilities, when NOT to route there — ending
    with the drill pointer when the child has its own knowledge store. Never
    a child's table-level detail; copying detail upward recreates context
    bloat one level up and rots when the child rebuilds.
    """

    source_kind = "root"

    INSTRUCTION = (
        "Write a concise ROUTING knowledge document about the child workflow "
        "described below, for a gateway agent deciding where to send a "
        "user's question. The VERY FIRST line of your answer must be a "
        "single-sentence index line of the exact form '<name> — <one-sentence "
        "what it does>'. Then: what questions it answers; its branches and "
        "capabilities (from the topology and description below); when NOT to "
        "use it. If the brief says the child has its own knowledge store, "
        "END the document with exactly this drill pointer sentence: 'This "
        "workflow has its own second brain — route there for depth.' If it "
        "does not, do not mention a second brain. Never copy table-level or "
        "field-level detail upward — this doc routes, the child answers. "
        "Markdown, no preamble, no code fences around the whole answer."
    )

    @staticmethod
    def mounted_slugs(document: dict[str, Any]) -> list[str]:
        """The children this document mounts, deduped, in canvas order.

        The one place that reads a mount's destination. Two mounts of the
        same child are one routing topic — the doc describes the child, not
        the edge — and canvas order keeps the build deterministic without
        imposing an alphabetical order the author did not choose.
        """
        slugs: list[str] = []
        for node in document.get("nodes") or []:
            if str(node.get("type") or "") not in _MOUNT_NODE_TYPES:
                continue
            data = node.get("data")
            if not isinstance(data, dict):
                continue
            slug = str(data.get("workflow") or "").strip()
            if slug and slug not in slugs:
                slugs.append(slug)
        return slugs

    def discover(
        self, workflow_dir: Path, document: dict[str, Any], workflows_root: Path
    ) -> Discovery:
        slugs = self.mounted_slugs(document)
        if not slugs:
            return Discovery()
        # Lazy import, same as the build endpoint's model resolution: the
        # domain layer must not hard-depend on the API package at import time.
        from openstategraph.api.workflow_store import WorkflowStore

        store = WorkflowStore(root=workflows_root)
        # Display names only exist on the envelope, and `list()` is the one
        # thing that parses envelopes. A mounted-but-hidden child is absent
        # from it, so its routing doc is titled by slug — which is what the
        # mount names anyway.
        names = {summary.slug: summary.name for summary in store.list()}
        topics: list[KnowledgeTopic] = []
        warnings: list[str] = []
        for slug in slugs:
            if slug == workflow_dir.name:
                # A self-mount is refused at compile time; here it would just
                # be a workflow writing a routing doc about itself.
                continue
            try:
                child_document = store.load(slug)
            except Exception as exc:
                warnings.append(
                    f"{slug}: mounted here, but its package could not be read "
                    f"({type(exc).__name__}) — no routing doc written"
                )
                continue
            topics.append(
                KnowledgeTopic(
                    name=slug,
                    brief=self.workflow_brief(
                        slug, names.get(slug, slug), workflows_root, child_document
                    ),
                    provenance=(
                        f"workflow.json topology and AGENTS.md of mounted child '{slug}'",
                    ),
                )
            )
        return Discovery(topics=topics, warnings=warnings)


# ---------------------------------------------------------------------------
# Project — the platform itself as a source, for a workflow that can see it.
# ---------------------------------------------------------------------------


class ProjectKnowledgeBuilder(AbstractWorkflowPointerBuilder):
    """**The project is a source, not a scope** — this is the project's second brain.

    The scope question the knowledge record left open ("one root store, or
    per-package stores with a root index?") is answered by refusing its
    premise. There is no project-level store, no project-level directory and
    no project-level scope concept, because a store is only worth writing
    where an agent is bound to read it, and binding is per package — one open
    document is one package is one ``knowledge/`` directory
    (``build-time-affordances.md``). A store at the workflows root would be
    Markdown no runtime reads.

    So the project joins the ladder the same way every other source does:
    **recognition from the wiring.** A ``tool.sql-*`` node's connection field
    means "a database is a source here"; a ``tool.platform-list-workflows`` /
    ``tool.platform-describe-workflow`` node means "**the project** is a
    source here", because that workflow can enumerate and describe every
    package on the platform at run time. Its topics land in its own
    ``knowledge/`` and are reached by the ``knowledge_lookup`` it already has
    ambiently. The project's second brain is therefore the union of the
    per-package ones, plus a catalogue held by whichever workflows can
    actually see the project — pointers all the way down, copies nowhere.

    **Topics = the packages those tools will show, minus this one, minus the
    ones this document mounts.** Each subtraction is read off a mechanism,
    never chosen:

    - *minus the visibility gate*: ``visible_to_platform_tools`` is imported
      from the tools themselves, so a catalogue entry can never name a
      package the agent's own ``platform_describe_workflow`` would then
      refuse to describe. This is ticket 16's rule applied in the other
      direction, and it is worth stating because the outcome inverts:
      ``RootKnowledgeBuilder`` **drops** the publish gate (a mount compiles
      the child as a subgraph and consults neither flag), and this builder
      **keeps** it (a platform tool enforces both). One rule — the gate
      belongs to the mechanism that reaches the destination — two opposite
      answers, and reading it off the mechanism is what makes that safe.
    - *minus the mounts*: a mounted child gets the strictly better
      routing-shaped doc from ``RootKnowledgeBuilder``. Partitioning the two
      topic sets by construction means the collision machinery (invariant 5)
      stays a backstop rather than firing on every build of a gateway.

    **Genre: a catalogue, not a routing table.** A routing doc says "send the
    question there"; a catalogue doc says "this exists, here is what it is
    for, and here is when it is the wrong answer". That last clause is the
    whole reason this is knowledge rather than introspection — the live tools
    already answer *what exists* and *what its topology is*, and neither can
    answer *when not to recommend it*. The concierge's own system prompt
    already makes that bet for its mounts: *"Look a workflow up before
    describing or recommending it"*, on an agent that also holds
    ``platform_describe_workflow``.
    """

    source_kind = "project"

    INSTRUCTION = (
        "Write a concise CATALOGUE knowledge document about one other "
        "workflow in this project, for an agent that has been asked what "
        "this platform offers or which workflow suits a task. The VERY FIRST "
        "line of your answer must be a single-sentence index line of the "
        "exact form '<name> — <one-sentence what it does>'. Then: what it is "
        "for; what kinds of question it answers well (from the topology and "
        "description below); and — most importantly — WHEN IT IS THE WRONG "
        "ANSWER, i.e. the questions people will wrongly bring to it. If the "
        "brief says it has its own knowledge store, END the document with "
        "exactly this drill pointer sentence: 'This workflow has its own "
        "second brain — open it for depth.' If it does not, do not mention a "
        "second brain. This workflow is NOT mounted here, so never tell the "
        "reader to route a question into it — say what it is, not how to "
        "call it. Never copy table-level or field-level detail upward. "
        "Markdown, no preamble, no code fences around the whole answer."
    )

    @staticmethod
    def reads_the_project(document: dict[str, Any]) -> bool:
        """Does this document wire a tool that can see the whole platform?"""
        return any(
            str(node.get("type") or "") in _PROJECT_NODE_TYPES
            for node in (document.get("nodes") or [])
        )

    def discover(
        self, workflow_dir: Path, document: dict[str, Any], workflows_root: Path
    ) -> Discovery:
        if not self.reads_the_project(document):
            return Discovery()
        # Lazy, for the same reason `RootKnowledgeBuilder` is: the domain
        # layer must not hard-depend on the API package at import time.
        from openstategraph.api.workflow_store import WorkflowStore
        from openstategraph.prebuilt_platform import visible_to_platform_tools

        root = workflows_root.resolve()
        store = WorkflowStore(root=workflows_root)
        mounted = set(RootKnowledgeBuilder.mounted_slugs(document))
        topics: list[KnowledgeTopic] = []
        warnings: list[str] = []
        for package in sorted(p for p in root.iterdir() if (p / "workflow.json").is_file()):
            slug = package.name
            if slug == workflow_dir.name or slug in mounted:
                continue
            try:
                envelope = json.loads((package / "workflow.json").read_text())
            except (OSError, ValueError) as exc:
                warnings.append(
                    f"{slug}: a package in this project whose workflow.json could "
                    f"not be read ({type(exc).__name__}) — no catalogue doc written"
                )
                continue
            if not isinstance(envelope, dict) or not visible_to_platform_tools(envelope):
                continue
            try:
                other_document = store.load(slug)
            except Exception as exc:
                warnings.append(
                    f"{slug}: visible in this project, but its package could not "
                    f"be loaded ({type(exc).__name__}) — no catalogue doc written"
                )
                continue
            name = str(envelope.get("name") or slug)
            topics.append(
                KnowledgeTopic(
                    name=slug,
                    brief=self.workflow_brief(slug, name, workflows_root, other_document),
                    provenance=(
                        f"workflow.json topology and AGENTS.md of project package '{slug}'",
                    ),
                )
            )
        return Discovery(topics=topics, warnings=warnings)


#: The extension point: register a builder here, never edit the endpoint.
#: Order is the escalation ladder — mechanical builders first, so they stamp
#: ownership of their topics before any agentic builder could claim them.
#: The agentic builders (`knowledge_explorer`) append themselves on import —
#: registration from their own module, because a top-level import either way
#: would be a cycle (they subclass `BaseKnowledgeBuilder`); `run_build`, the
#: only consumer of the agentic path, imports that module.
#: ``RootKnowledgeBuilder`` before ``ProjectKnowledgeBuilder`` so a mounted
#: child's routing doc is written before anything could catalogue it — the
#: project builder subtracts the mounts anyway, so this is the backstop, not
#: the mechanism.
BUILDERS: list[BaseKnowledgeBuilder] = [
    SqlKnowledgeBuilder(),
    RootKnowledgeBuilder(),
    ProjectKnowledgeBuilder(),
]


__all__ = [
    "BUILDERS",
    "CLAIMED_HASH_COMMENT",
    "claimed_hash",
    "marker_hash",
    "source_hash",
    "GENERATED_MARKER",
    "AbstractWorkflowPointerBuilder",
    "BaseKnowledgeBuilder",
    "Discovery",
    "IKnowledgeBuilder",
    "KnowledgeTopic",
    "ProjectKnowledgeBuilder",
    "RootKnowledgeBuilder",
    "SqlKnowledgeBuilder",
    "marker_source",
    "sql_sources_in_document",
]
