"""Second-brain builders: ``IKnowledgeBuilder`` → ``BaseKnowledgeBuilder`` → concretes.

The *builders* are the open extension point of the knowledge layer — the
store and the lookup tool (``knowledge.py``, ``prebuilt_knowledge.py``) stay
exactly one store and one tool regardless of which builder wrote a doc. A
topic is a topic: once ``knowledge/<topic>.md`` exists, nothing downstream
knows or cares which source produced it. The files are plain Markdown in
git, read both by workflow agents at runtime (through the lookup tool) and
by any coding agent opening ``workflows/<slug>/knowledge/*.md`` directly.

A builder answers two questions:

- ``discover(workflow_dir, document, workflows_root)`` — which topics does
  this workflow have, from *my* kind of source? Each topic carries its own
  **brief**: the raw source material (a schema, a directory tree, a spec
  fragment) the model turns into a procedural doc.
- ``build(topic, model)`` — one model call, composed by the base: the shared
  write-a-procedural-doc instruction plus the topic's brief.

The base owns everything shared — prompt composition, the model invocation,
the generated-marker header, and the write-with-regeneration-policy — so a
new source is *only* a ``discover`` implementation registered in
``BUILDERS``. Never edit the endpoint to add a source.

**Regeneration policy** (chosen and documented, per the spec): a doc whose
first line carries ``GENERATED_MARKER`` belongs to the builder and is
overwritten on every build; a file *without* the marker is hand-authored and
is never touched — it is reported as skipped. Hand-tuning a generated doc is
therefore one deliberate act: delete the marker line and the file is yours.

Planned concretes, recorded here so the shape is designed for them rather
than retrofitted:

- ``CodebaseKnowledgeBuilder`` — indexes an application/repo structure (the
  graphify/OpenWiki move): topics are modules or bounded contexts, briefs
  are directory trees and public surfaces. Doubly useful because the output
  is exactly what a *coding* agent wants to read before editing the same
  package.
- ``ApiKnowledgeBuilder`` — OpenAPI specs (the ``open-api-explorer``
  workflow): topics are resources/endpoints, briefs are the spec fragments.
"""

from __future__ import annotations

import sqlite3
from abc import ABC, abstractmethod
from dataclasses import dataclass
from pathlib import Path
from typing import Any, ClassVar, Protocol, runtime_checkable

from openstategraph.knowledge import BaseKnowledge

#: First line of every builder-owned doc. Its absence marks a file as
#: hand-authored and untouchable — see the module docstring's policy.
GENERATED_MARKER = "<!-- generated by build-second-brain"

_GENERATED_HEADER = (
    f"{GENERATED_MARKER}; regenerate via POST /api/workflows/<slug>/knowledge/build; "
    "delete this line to claim the file as hand-authored -->"
)

#: The node types whose config names a SQL database, and the bundled default
#: the chinook-* family is hard-wired to.
_SQL_NODE_PREFIX = "tool.sql-"
_CHINOOK_NODE_PREFIX = "tool.chinook-"
_CHINOOK_DATABASE = "chinook-nl-to-sql/data/Chinook_Sqlite.sqlite"


@dataclass(frozen=True)
class KnowledgeTopic:
    """One buildable topic: its name and the source material for the model."""

    name: str
    brief: str


@runtime_checkable
class IKnowledgeBuilder(Protocol):
    """The contract the build endpoint depends on — a shape, not a class."""

    source_kind: str

    def discover(
        self, workflow_dir: Path, document: dict[str, Any], workflows_root: Path
    ) -> list[KnowledgeTopic]: ...

    def build(self, topic: KnowledgeTopic, model: Any) -> str: ...


class BaseKnowledgeBuilder(ABC):
    """Shared machinery: prompt composition, model call, marker, writing.

    A concrete supplies ``source_kind`` and ``discover``; everything else —
    including the regeneration policy — is declared once here.
    """

    source_kind: ClassVar[str]

    #: The shared instruction. The topic's brief is context; this is the
    #: task. Concretes never restate it.
    INSTRUCTION = (
        "Write a concise procedural knowledge document for the topic below, "
        "for an AI agent that will use this source at runtime. Infer and "
        "state the business meaning; explain each column or member's "
        "semantics; spell out the JOIN rules / relationships explicitly; "
        "note caveats (nullable fields, units, encodings, gotchas visible in "
        "the sample). Markdown, no preamble, no code fences around the "
        "whole answer."
    )

    @abstractmethod
    def discover(
        self, workflow_dir: Path, document: dict[str, Any], workflows_root: Path
    ) -> list[KnowledgeTopic]:
        """Every topic this builder can write for this workflow."""

    def compose_prompt(self, topic: KnowledgeTopic) -> str:
        return f"{self.INSTRUCTION}\n\n# Topic: {topic.name}\n\n{topic.brief}"

    def build(self, topic: KnowledgeTopic, model: Any) -> str:
        """One model call → the doc body. The write is `write()`'s job."""
        response = model.invoke(self.compose_prompt(topic))
        return str(getattr(response, "content", response)).strip()

    def target_path(self, workflow_dir: Path, topic: KnowledgeTopic) -> Path:
        return workflow_dir / "knowledge" / f"{BaseKnowledge.normalize(topic.name)}.md"

    def owns(self, workflow_dir: Path, topic: KnowledgeTopic) -> bool:
        """False for a hand-authored file (no marker) — the builder must not
        touch it, and the orchestrator should not even spend a model call."""
        path = self.target_path(workflow_dir, topic)
        return not (path.is_file() and not path.read_text().startswith(GENERATED_MARKER))

    def write(self, workflow_dir: Path, topic: KnowledgeTopic, body: str) -> bool:
        """Writes ``knowledge/<topic>.md``; False means hand-authored, kept."""
        if not self.owns(workflow_dir, topic):
            return False
        path = self.target_path(workflow_dir, topic)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(f"{_GENERATED_HEADER}\n\n# {topic.name}\n\n{body}\n")
        return True


# ---------------------------------------------------------------------------
# SQL — the first concrete: one topic per table of each configured database.
# ---------------------------------------------------------------------------


def databases_in_document(document: dict[str, Any], workflows_root: Path) -> list[Path]:
    """Every SQL database this document's tool nodes point at.

    Read from the same fields the SQL Explorer nodes are configured with
    (``tool.sql-*``'s ``database``), plus the bundled Chinook database when
    any ``tool.chinook-*`` node is present. Jailed to the workflows root and
    limited to files that exist — a bad path is a skipped source, never an
    escape hatch.
    """
    root = workflows_root.resolve()
    found: list[Path] = []
    for node in document.get("nodes") or []:
        node_type = str(node.get("type") or "")
        relative = ""
        if node_type.startswith(_SQL_NODE_PREFIX):
            relative = str((node.get("data") or {}).get("database") or "").strip()
        elif node_type.startswith(_CHINOOK_NODE_PREFIX):
            relative = _CHINOOK_DATABASE
        if not relative:
            continue
        candidate = (root / relative).resolve()
        try:
            candidate.relative_to(root)
        except ValueError:
            continue
        if candidate.is_file() and candidate not in found:
            found.append(candidate)
    return found


def _connect(path: Path) -> sqlite3.Connection:
    return sqlite3.connect(f"file:{path}?mode=ro", uri=True)


def _table_names(conn: sqlite3.Connection) -> list[str]:
    return [
        r[0]
        for r in conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' "
            "AND name NOT LIKE 'sqlite_%' ORDER BY name"
        )
    ]


def table_brief(database: Path, table: str, sample_rows: int = 5) -> str:
    """Everything the model needs about one table: full schema (columns,
    types, PKs, FKs **both directions**) and a small data sample."""
    with _connect(database) as conn:
        columns = [
            f"- {r[1]} ({r[2] or 'ANY'})" + (" PRIMARY KEY" if r[5] else "")
            for r in conn.execute(f'PRAGMA table_info("{table}")')
        ]
        outbound = [
            f"- JOIN rule: {table}.{r[3]} references {r[2]}.{r[4]}"
            for r in conn.execute(f'PRAGMA foreign_key_list("{table}")')
        ]
        inbound = []
        for other in _table_names(conn):
            if other == table:
                continue
            for r in conn.execute(f'PRAGMA foreign_key_list("{other}")'):
                if r[2] == table:
                    inbound.append(
                        f"- JOIN rule (referenced by): {other}.{r[3]} references {table}.{r[4]}"
                    )
        cursor = conn.execute(f'SELECT * FROM "{table}" LIMIT {int(sample_rows)}')
        headers = [d[0] for d in cursor.description or []]
        sample = [
            "| " + " | ".join(headers) + " |",
            "| " + " | ".join("---" for _ in headers) + " |",
            *("| " + " | ".join(str(c) for c in row) + " |" for row in cursor.fetchall()),
        ]
    parts = ["## Columns", *columns]
    if outbound:
        parts += ["\n## Foreign keys (outbound)", *outbound]
    if inbound:
        parts += ["\n## Foreign keys (inbound)", *inbound]
    parts += ["\n## Data sample", *sample]
    return "\n".join(parts)


class SqlKnowledgeBuilder(BaseKnowledgeBuilder):
    """One topic per table of every database the workflow's SQL tools use."""

    source_kind = "sql"

    def discover(
        self, workflow_dir: Path, document: dict[str, Any], workflows_root: Path
    ) -> list[KnowledgeTopic]:
        topics: list[KnowledgeTopic] = []
        seen: set[str] = set()
        for database in databases_in_document(document, workflows_root):
            with _connect(database) as conn:
                tables = _table_names(conn)
            for table in tables:
                key = BaseKnowledge.normalize(table)
                if key in seen:
                    continue  # same-named table in a second database: first wins
                seen.add(key)
                topics.append(KnowledgeTopic(name=table, brief=table_brief(database, table)))
        return topics


#: The extension point: register a builder here, never edit the endpoint.
BUILDERS: list[BaseKnowledgeBuilder] = [SqlKnowledgeBuilder()]


__all__ = [
    "BUILDERS",
    "GENERATED_MARKER",
    "BaseKnowledgeBuilder",
    "IKnowledgeBuilder",
    "KnowledgeTopic",
    "SqlKnowledgeBuilder",
    "databases_in_document",
    "table_brief",
]
