"""Second-brain builders: ``IKnowledgeBuilder`` → ``BaseKnowledgeBuilder`` → concretes.

The *builders* are the open extension point of the knowledge layer — the
store and the lookup tool (``knowledge.py``, ``prebuilt_knowledge.py``) stay
exactly one store and one tool regardless of which builder wrote a doc. A
topic is a topic: once ``knowledge/<topic>.md`` exists, nothing downstream
knows or cares which source produced it. The files are plain Markdown in
git, read both by workflow agents at runtime (through the lookup tool) and
by any coding agent opening ``workflows/<slug>/knowledge/*.md`` directly.

A builder answers two questions:

- ``discover(workflow_dir, document, workflows_root)`` — which topics does
  this workflow have, from *my* kind of source? Each topic carries its own
  **brief**: the raw source material (a schema, a directory tree, a spec
  fragment) the model turns into a procedural doc. Discovery also reports
  **warnings** — a source it recognized but could not open (a missing
  optional driver) is reported, never silently dropped and never a crash.
- ``build(topic, model)`` — one model call, composed by the base: the shared
  write-a-procedural-doc instruction plus the topic's brief.

The base owns everything shared — prompt composition, the model invocation,
the generated-marker header, and the write-with-regeneration-policy — so a
new source is *only* a ``discover`` implementation registered in
``BUILDERS``. Never edit the endpoint to add a source.

**Regeneration policy** (invariant 5 of the knowledge architecture): the
marker line records the *owning builder* (``source=<kind>``). ``owns()``
gates regeneration three ways —

- no marker → hand-authored, never touched, reported as skipped;
- marker naming *this* builder (or the legacy marker with no source, from
  docs written before ownership was recorded) → owned, regenerated;
- marker naming a *different* builder → a cross-builder topic collision,
  **refused and reported**, never last-write-wins.

Hand-tuning a generated doc is therefore one deliberate act: delete the
marker line and the file is yours.

**Every generated doc opens with its index line** — a one-sentence summary
right after the marker — because ``PackageKnowledge.topics()`` serves the
first meaningful line of each doc as the free index tier: authoring the doc
authors the index.
"""

from __future__ import annotations

import hashlib
import re
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, ClassVar, Protocol, runtime_checkable

from openstategraph.knowledge import BaseKnowledge
from openstategraph.knowledge_engines import ENGINE_ADAPTERS, SqliteEngineAdapter, recognize

#: First line prefix of every builder-owned doc. Its absence marks a file as
#: hand-authored and untouchable — see the module docstring's policy.
GENERATED_MARKER = "<!-- generated by build-second-brain"

_MARKER_SOURCE_RE = re.compile(r"source=([a-z0-9-]+)")
_MARKER_HASH_RE = re.compile(r"hash=([0-9a-f]{12})")
#: The claim-time hash record on a claimed (hand-owned) doc: a trailing HTML
#: comment, chosen over a sidecar file as the least-invasive spelling — the
#: doc stays one self-contained file in git, and Markdown renderers hide it.
CLAIMED_HASH_COMMENT = "<!-- knowledge-claimed source-hash="
_CLAIMED_HASH_RE = re.compile(
    re.escape(CLAIMED_HASH_COMMENT) + r"([0-9a-f]{12}) -->"
)


def source_hash(brief: str) -> str:
    """A short content hash of a topic's introspection input (its brief).

    Stamped into the generated marker at build time and recorded on claimed
    docs at claim time; the curation list compares it against the current
    source's recomputed hash to badge staleness ("the source behind this doc
    changed") — you keep the pen; you lose the ignorance.
    """
    return hashlib.sha256(brief.encode()).hexdigest()[:12]


def marker_hash(text: str) -> str | None:
    """The source hash a generated doc's marker stamped, if any."""
    if not text.startswith(GENERATED_MARKER):
        return None
    match = _MARKER_HASH_RE.search(text.splitlines()[0])
    return match.group(1) if match else None


def claimed_hash(text: str) -> str | None:
    """The claim-time source hash a claimed doc's trailing comment records."""
    match = _CLAIMED_HASH_RE.search(text)
    return match.group(1) if match else None

#: The node types whose config names a SQL database, and the bundled default
#: the chinook-* family is hard-wired to.
_SQL_NODE_PREFIX = "tool.sql-"
_CHINOOK_NODE_PREFIX = "tool.chinook-"
_CHINOOK_DATABASE = "chinook-nl-to-sql/data/Chinook_Sqlite.sqlite"

#: The mount node types that make a workflow "root-ish" — see
#: ``RootKnowledgeBuilder``'s discovery rule.
_MOUNT_NODE_TYPES = ("workflow.subgraph", "team.workflow")


def marker_source(text: str) -> str | None:
    """The owning builder a doc's marker records.

    None → no marker, hand-authored. ``""`` → the legacy marker written
    before ownership was recorded (owned by whichever builder claims the
    topic). Otherwise the ``source=<kind>`` of the owning builder.
    """
    if not text.startswith(GENERATED_MARKER):
        return None
    first_line = text.splitlines()[0]
    match = _MARKER_SOURCE_RE.search(first_line)
    return match.group(1) if match else ""


@dataclass(frozen=True)
class KnowledgeTopic:
    """One buildable topic: its name and the source material for the model."""

    name: str
    brief: str
    #: What the builder actually looked at (tables/files/tools) — becomes the
    #: doc's provenance footer, so a wrong claim is auditable to its source.
    provenance: tuple[str, ...] = ()


@dataclass(frozen=True)
class Discovery:
    """What one builder found in one workflow: topics, plus the sources it
    recognized but could not open (reported, never a crash)."""

    topics: list[KnowledgeTopic] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


@runtime_checkable
class IKnowledgeBuilder(Protocol):
    """The contract the build endpoint depends on — a shape, not a class."""

    source_kind: str

    def discover(
        self, workflow_dir: Path, document: dict[str, Any], workflows_root: Path
    ) -> Discovery: ...

    def build(self, topic: KnowledgeTopic, model: Any) -> str: ...


class BaseKnowledgeBuilder(ABC):
    """Shared machinery: prompt composition, model call, marker, writing.

    A concrete supplies ``source_kind`` and ``discover``; everything else —
    including the regeneration and ownership policy — is declared once here.
    """

    source_kind: ClassVar[str]

    #: The shared instruction. The topic's brief is context; this is the
    #: task. Concretes never restate it (they may override it wholesale when
    #: their docs are a different genre — see ``RootKnowledgeBuilder``).
    INSTRUCTION = (
        "Write a concise procedural knowledge document for the topic below, "
        "for an AI agent that will use this source at runtime. The VERY "
        "FIRST line of your answer must be a single-sentence summary of the "
        "topic ('<topic> — <what it is and what questions it answers>'); "
        "this line becomes the topic's entry in the knowledge index. Then "
        "the document: infer and state the business meaning; explain each "
        "column or member's semantics; spell out the JOIN rules / "
        "relationships explicitly; note caveats (nullable fields, units, "
        "encodings, gotchas visible in the sample). Markdown, no preamble, "
        "no code fences around the whole answer."
    )

    @abstractmethod
    def discover(
        self, workflow_dir: Path, document: dict[str, Any], workflows_root: Path
    ) -> Discovery:
        """Every topic this builder can write for this workflow, plus
        warnings for recognized-but-unavailable sources."""

    def compose_prompt(self, topic: KnowledgeTopic) -> str:
        return f"{self.INSTRUCTION}\n\n# Topic: {topic.name}\n\n{topic.brief}"

    def build(self, topic: KnowledgeTopic, model: Any) -> str:
        """One model call → the doc body. The write is `write()`'s job."""
        response = model.invoke(self.compose_prompt(topic))
        return str(getattr(response, "content", response)).strip()

    def marker_header(self, topic: KnowledgeTopic | None = None) -> str:
        """The marker line: this builder as owner, plus the source content
        hash (of the topic's brief) the staleness badge compares against.
        Agentic builders have no recomputable brief, so no hash is stamped."""
        stamp = f" hash={source_hash(topic.brief)}" if topic is not None and topic.brief else ""
        return (
            f"{GENERATED_MARKER} source={self.source_kind}{stamp}; regenerate via "
            "POST /api/workflows/<slug>/knowledge/build; delete this line to "
            "claim the file as hand-authored -->"
        )

    def target_path(self, workflow_dir: Path, topic: KnowledgeTopic) -> Path:
        return workflow_dir / "knowledge" / f"{BaseKnowledge.normalize(topic.name)}.md"

    def owns(self, workflow_dir: Path, topic: KnowledgeTopic) -> bool:
        """May this builder (re)generate this topic's file?

        True for an absent file, a marker naming this builder, or the legacy
        marker with no source. False for a hand-authored file (no marker)
        AND for a marker naming a different builder — use ``collides_with``
        to tell the two refusals apart.
        """
        path = self.target_path(workflow_dir, topic)
        if not path.is_file():
            return True
        owner = marker_source(path.read_text())
        return owner in ("", self.source_kind)

    def collides_with(self, workflow_dir: Path, topic: KnowledgeTopic) -> str | None:
        """The *other* builder that owns this topic's file, if any."""
        path = self.target_path(workflow_dir, topic)
        if not path.is_file():
            return None
        owner = marker_source(path.read_text())
        if owner is None or owner in ("", self.source_kind):
            return None
        return owner

    def write(self, workflow_dir: Path, topic: KnowledgeTopic, body: str) -> bool:
        """Writes ``knowledge/<topic>.md``; False means not owned, kept.

        The body's first line is the doc's index line (the drafting
        instruction demands it), so the layout is marker, blank line, body —
        no injected heading between the marker and the index line.
        """
        if not self.owns(workflow_dir, topic):
            return False
        path = self.target_path(workflow_dir, topic)
        path.parent.mkdir(parents=True, exist_ok=True)
        footer = ""
        if topic.provenance:
            footer = (
                "\n\n---\n_Provenance: built from "
                + "; ".join(topic.provenance)
                + "._"
            )
        path.write_text(f"{self.marker_header(topic)}\n\n{body}{footer}\n")
        return True


# ---------------------------------------------------------------------------
# SQL — one topic per table, generic over engines via the adapter seam.
# ---------------------------------------------------------------------------


def databases_in_document(document: dict[str, Any], workflows_root: Path) -> list[Path]:
    """Every SQLite database file this document's tool nodes point at.

    Kept for the SQLite path (jailed to the workflows root, limited to files
    that exist — a bad path is a skipped source, never an escape hatch).
    URL-schemed refs are the adapter seam's business: see
    ``sql_sources_in_document``.
    """
    return [
        workflows_root.resolve() / ref
        for ref, engine in sql_sources_in_document(document, workflows_root)
        if engine == "sqlite"
    ]


def sql_sources_in_document(
    document: dict[str, Any], workflows_root: Path
) -> list[tuple[str, str]]:
    """Every recognized SQL source in the document, as ``(ref, engine)``.

    Recognition reads the wiring (``knowledge_engines.recognize``): a bare
    path is SQLite (jailed to the workflows root, must exist; the ref is
    normalized to root-relative), a ``postgres://``/``mssql://`` URL names
    its engine and is passed through for the adapter to open.
    """
    root = workflows_root.resolve()
    found: list[tuple[str, str]] = []
    seen: set[str] = set()
    for node in document.get("nodes") or []:
        node_type = str(node.get("type") or "")
        ref = ""
        if node_type.startswith(_SQL_NODE_PREFIX):
            ref = str((node.get("data") or {}).get("database") or "").strip()
        elif node_type.startswith(_CHINOOK_NODE_PREFIX):
            ref = _CHINOOK_DATABASE
        if not ref:
            continue
        engine = recognize(ref)
        if engine is None:
            continue
        if engine == "sqlite" and "://" not in ref:
            candidate = (root / ref).resolve()
            try:
                candidate.relative_to(root)
            except ValueError:
                continue
            if not candidate.is_file():
                continue
            ref = str(candidate.relative_to(root))
        if ref in seen:
            continue
        seen.add(ref)
        found.append((ref, engine))
    return found


def table_brief(database: Path, table: str, sample_rows: int = 5) -> str:
    """One SQLite table's brief — schema (FKs both directions) + sample.

    A thin veneer over the SQLite adapter, kept as the module's historical
    public name."""
    return SqliteEngineAdapter().table_brief(str(database), table, sample_rows)


class SqlKnowledgeBuilder(BaseKnowledgeBuilder):
    """One topic per table of every SQL source the workflow's tools use.

    Engines are the adapter seam's business (``knowledge_engines``): this
    builder recognizes refs from the wiring, asks the matching adapter for
    tables and briefs, and reports a recognized source whose driver is
    missing as a warning — never a crash, never a silent skip.
    """

    source_kind = "sql"

    def discover(
        self, workflow_dir: Path, document: dict[str, Any], workflows_root: Path
    ) -> Discovery:
        root = workflows_root.resolve()
        topics: list[KnowledgeTopic] = []
        warnings: list[str] = []
        seen: set[str] = set()
        for ref, engine in sql_sources_in_document(document, workflows_root):
            adapter = ENGINE_ADAPTERS[engine]
            usable, warning = adapter.available()
            if not usable:
                warnings.append(
                    f"{ref}: recognized as {engine}, but unavailable — {warning}"
                )
                continue
            connection_ref = str(root / ref) if engine == "sqlite" else ref
            for table in adapter.list_tables(connection_ref):
                key = BaseKnowledge.normalize(table)
                if key in seen:
                    continue  # same-named table in a second source: first wins
                seen.add(key)
                topics.append(
                    KnowledgeTopic(
                        name=table,
                        brief=adapter.table_brief(connection_ref, table),
                        provenance=(f"table {table} of {ref} ({engine} schema + sample)",),
                    )
                )
        return Discovery(topics=topics, warnings=warnings)


# ---------------------------------------------------------------------------
# Root — one coarse routing doc per visible child workflow.
# ---------------------------------------------------------------------------


class RootKnowledgeBuilder(BaseKnowledgeBuilder):
    """Topics = the platform's visible child workflows; docs written to route.

    **Discovery rule (documented, deliberate):** this builder only finds
    topics when the workflow being built is *root-ish* — concretely, when
    its document mounts children (any ``workflow.subgraph`` or
    ``team.workflow`` node) OR its slug is ``concierge`` (the gateway is
    hidden and root by definition, even while its mounts are being edited).
    Any other workflow yields no topics, so the builder never fires on a
    leaf.

    Hierarchy means pointers, not copies: each doc is one coarse page — what
    the child answers, its capabilities, when NOT to route there — ending
    with the drill pointer when the child has its own knowledge store. Never
    a child's table-level detail; copying detail upward recreates context
    bloat one level up and rots when the child rebuilds.
    """

    source_kind = "root"

    INSTRUCTION = (
        "Write a concise ROUTING knowledge document about the child workflow "
        "described below, for a gateway agent deciding where to send a "
        "user's question. The VERY FIRST line of your answer must be a "
        "single-sentence index line of the exact form '<name> — <one-sentence "
        "what it does>'. Then: what questions it answers; its branches and "
        "capabilities (from the topology and description below); when NOT to "
        "use it. If the brief says the child has its own knowledge store, "
        "END the document with exactly this drill pointer sentence: 'This "
        "workflow has its own second brain — route there for depth.' If it "
        "does not, do not mention a second brain. Never copy table-level or "
        "field-level detail upward — this doc routes, the child answers. "
        "Markdown, no preamble, no code fences around the whole answer."
    )

    def _is_root(self, workflow_dir: Path, document: dict[str, Any]) -> bool:
        if workflow_dir.name == "concierge":
            return True
        return any(
            str(node.get("type") or "") in _MOUNT_NODE_TYPES
            for node in document.get("nodes") or []
        )

    def discover(
        self, workflow_dir: Path, document: dict[str, Any], workflows_root: Path
    ) -> Discovery:
        if not self._is_root(workflow_dir, document):
            return Discovery()
        # Lazy import, same as the build endpoint's model resolution: the
        # domain layer must not hard-depend on the API package at import time.
        from openstategraph.api.workflow_store import WorkflowStore

        store = WorkflowStore(root=workflows_root)
        topics: list[KnowledgeTopic] = []
        for summary in store.list():  # list() already excludes hidden workflows
            if summary.slug == workflow_dir.name:
                continue
            topics.append(
                KnowledgeTopic(
                    name=summary.slug,
                    brief=self._child_brief(summary.slug, summary.name, workflows_root, store),
                    provenance=(
                        f"workflow.json topology and AGENTS.md of child '{summary.slug}'",
                    ),
                )
            )
        return Discovery(topics=topics)

    def _child_brief(
        self, slug: str, name: str, workflows_root: Path, store: Any
    ) -> str:
        child_dir = workflows_root / slug
        try:
            document = store.load(slug)
        except Exception:
            document = {}
        parts = [f"Child workflow: {name} (slug: {slug})"]
        parts.append(self._topology(document))
        agents_md = child_dir / "AGENTS.md"
        if agents_md.is_file():
            head = "\n".join(agents_md.read_text().splitlines()[:30]).strip()
            if head:
                parts.append(f"## Description (AGENTS.md head)\n{head}")
        if any((child_dir / "knowledge").glob("*.md")):
            parts.append(
                "This child HAS its own knowledge store (a second brain) — "
                "end the doc with the drill pointer."
            )
        else:
            parts.append("This child has no knowledge store of its own.")
        return "\n\n".join(parts)

    @staticmethod
    def _topology(document: dict[str, Any]) -> str:
        """What the canvas itself says the child can do — node types, router
        branches, and mounted grandchildren, mechanically derived."""
        nodes = document.get("nodes") or []
        lines = ["## Topology"]
        types = sorted({str(n.get("type") or "") for n in nodes if n.get("type")})
        if types:
            lines.append("Node types: " + ", ".join(types))
        for node in nodes:
            data = node.get("data") if isinstance(node, dict) else None
            if not isinstance(data, dict):
                continue
            raw_branches = data.get("branches")
            branches = [
                str(b.get("name") or "")
                for b in (raw_branches if isinstance(raw_branches, list) else [])
                if isinstance(b, dict)
            ]
            if branches:
                lines.append(f"Router branches: {', '.join(b for b in branches if b)}")
            if str(node.get("type") or "") in _MOUNT_NODE_TYPES and data.get("workflow"):
                lines.append(f"Mounts child workflow: {data['workflow']}")
        return "\n".join(lines)


#: The extension point: register a builder here, never edit the endpoint.
#: Order is the escalation ladder — mechanical builders first, so they stamp
#: ownership of their topics before any agentic builder could claim them.
#: The agentic builders (`knowledge_explorer`) append themselves on import —
#: registration from their own module, because a top-level import either way
#: would be a cycle (they subclass `BaseKnowledgeBuilder`); `run_build`, the
#: only consumer of the agentic path, imports that module.
BUILDERS: list[BaseKnowledgeBuilder] = [SqlKnowledgeBuilder(), RootKnowledgeBuilder()]


__all__ = [
    "BUILDERS",
    "CLAIMED_HASH_COMMENT",
    "claimed_hash",
    "marker_hash",
    "source_hash",
    "GENERATED_MARKER",
    "BaseKnowledgeBuilder",
    "Discovery",
    "IKnowledgeBuilder",
    "KnowledgeTopic",
    "RootKnowledgeBuilder",
    "SqlKnowledgeBuilder",
    "databases_in_document",
    "marker_source",
    "sql_sources_in_document",
    "table_brief",
]
