// Generated by scripts/generate_gap_report_ts.py from
// openstategraph.gap_report.GapReport — never hand-edited, and checked by
// `python3 scripts/generate_gap_report_ts.py --check`.
//
// The report's vocabulary, in the door's own language: which fields a report
// may carry, which it must carry, which values each enum accepts, how long a
// carried sentence may be, and which board a filed report lands on. The
// validator that consumes this is hand-written in `index.ts`
// (team-board-and-gap-reports/09, `17`).

export const CONTRACT = {
  "board": "osgEngineering",
  "category": "gap",
  "fields": {
    "aad_code": {
      "kind": "nullableString"
    },
    "check": {
      "kind": "nullableString"
    },
    "door": {
      "kind": "enum",
      "values": [
        "api",
        "mcp",
        "cli",
        "library",
        "editor"
      ]
    },
    "finding_hash": {
      "kind": "string"
    },
    "kind": {
      "kind": "enum",
      "values": [
        "no-backend",
        "node-failure",
        "every-tool-call-failed",
        "provider-not-configured",
        "door-refused"
      ]
    },
    "os": {
      "kind": "string"
    },
    "project_hash": {
      "kind": "string"
    },
    "python": {
      "kind": "string"
    },
    "refusal": {
      "kind": "refusal"
    },
    "traceback_line": {
      "kind": "nullableString"
    },
    "type_ids": {
      "kind": "stringArray"
    },
    "version": {
      "kind": "string"
    }
  },
  "refusalFields": [
    "source",
    "text"
  ],
  "refusalRequired": [
    "source",
    "text"
  ],
  "refusalSources": [
    "runtime",
    "provider",
    "exception",
    "finding"
  ],
  "required": [
    "kind",
    "door",
    "refusal",
    "project_hash",
    "finding_hash"
  ],
  "textCap": 400
} as const;
